plugins:
  - jekyll-sass-converter
  - jekyll-coffeescript

sass:
sass_dir: _sass
style: compressed

title: Flavournomics - Find Your Flavour of economics

description: My personal Blog

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
