# Site settings
title: Flavournomics - Find Your Flavour of economics
description: My personal Blog

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
 - jekyll-sass-converter
 - jekyll-coffeescript